# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StkPush_Online_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_short_code', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=250)),
                ('timestamp', models.DateField()),
                ('transaction_type', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('party_a', models.CharField(max_length=100)),
                ('party_b', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('callback_url', models.CharField(max_length=100)),
                ('account_reference', models.CharField(max_length=12)),
                ('tansacrion_description', models.CharField(max_length=13)),
            ],
        ),
    ]
