# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StkPush_Online_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_short_code', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField()),
                ('transaction_type', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('party_a', models.CharField(max_length=100)),
                ('party_b', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('callback_url', models.CharField(max_length=100)),
                ('account_reference', models.CharField(max_length=12)),
                ('tansaction_description', models.CharField(max_length=13)),
                ('date_done', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
