# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StkPush_Call_Back',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.PositiveIntegerField(blank=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=250, null=True)),
                ('result_code', models.PositiveIntegerField(blank=True)),
                ('result_description', models.CharField(blank=True, max_length=250, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
