# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpush_online_payment',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
