# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0002_stkpush_call_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpush_call_back',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stkpush_call_back',
            name='result_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
