# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 10:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('literacy', '0002_auto_20180829_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkpush_online_payment',
            name='date_done',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 8, 29, 10, 58, 25, 471339, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stkpush_online_payment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stkpush_online_payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
