# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0003_auto_20180913_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpush_online_payment',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
