# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0004_auto_20180914_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpush_online_payment',
            name='timestamp',
            field=models.CharField(max_length=50),
        ),
    ]
