# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0011_auto_20180919_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactions',
            name='result_description',
            field=models.TextField(),
        ),
    ]
