# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0014_auto_20180921_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='plan',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
