# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0016_auto_20180921_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='unique_reference_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
