# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy', '0018_auto_20180924_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactions',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
